import Navigation from '@/components/navigation/navigation'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function CustomerLayout({ children }) {
  return (
    <div className={`${inter.className} h-screen`}>
      <Navigation />
      {children}
    </div>
  )
}
